FROM mcr.microsoft.com/dotnet/sdk:7.0

WORKDIR /app

COPY . .

# RUN dotnet restore

# RUN dotnet publish ./WindowsCalc.csproj -c Release -r win-x64 --self-contained false -v minimal

# RUN cp /app/bin/Release/net7.0/win-x64/publish/WindowsCalc.exe .
